export const softwareEngineers = [
  {
    name: "John Smith",
    age: 25,
    title: "Cloud Engineer",
    gender: "Male",
    location: "San Francisco, CA",
    experience: 2,
    skills: ["Java", "Python", "JavaScript"],
    interests: ["Photography", "Swimming"],
    department: "Electrical Engineering",
  },
  {
    name: "Jane Doe",
    age: 30,
    title: "Frontend Engineer",
    gender: "Female",
    location: "New York, NY",
    experience: 5,
    skills: ["C++", "C#", "SQL"],
    interests: ["Photography", "Swimming"],
    department: "Computer Engineering",
  },
  {
    name: "Bob Jones",
    title: "Software Engineer",
    age: 35,
    gender: "Male",
    location: "Seattle, WA",
    experience: 10,
    skills: ["Ruby", "Rails", "React"],
    interests: ["Walking", "Running"],
    department: "Civil Engineering",
  },
  {
    name: "Sarah Williams",
    title: "Ethical Hacker",
    age: 40,
    gender: "Female",
    location: "Austin, TX",
    experience: 15,
    skills: ["Angular", "Node.js", "Docker"],
    interests: ["Football", "Playing Chess"],
    department: "Electrical Engineering",
  },
  {
    name: "David Brown",
    title: "Backend Developer",
    age: 45,
    gender: "Male",
    location: "Chicago, IL",
    experience: 20,
    skills: ["Go", "Kotlin", "AWS"],
    interests: ["Playing cricket", "Hockey"],
  },
];
